apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
helmCharts:
- name: ingress-nginx
  namespace: ingress-nginx
  releaseName: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  valuesFile: values.yaml
  version: 4.12.0
resources:
- ./templates/namespaces/nginx-ingress-namespace.yaml