apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
helmCharts:
- name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  version: 1.17.1
resources:
- ./templates/namespaces/cert-manager-namespace.yaml
- ./templates/secrets/cert-manager-secret.yaml
- ./templates/issuers/cert-manager-issuer.yaml
- ./templates/certificates/cert-manager-certificate.yaml
