apiVersion: v1
kind: Service
metadata:
  name: pgpool-service
  namespace: pgpool
spec:
  selector:
    app: pgpool
  ports:
    - name: pgpool
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP 