apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "5432": cnpg-database/postgresql-cluster-rw:5432 # Forward TCP traffic on port 5432 to the PostgreSQL cluster
