apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: reflector
helmCharts:
- name: reflector
  namespace: kube-system
  releaseName: reflector
  repo: https://emberstack.github.io/helm-charts
  version: 9.0.322
