apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: pgbouncer
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 6432
      targetPort: 6432
  type: ClusterIP 