apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nodejs
          image: technicaldirector/nextjs:1 # Change this to your created dockerhub repo
          # image: ghcr.io/technicaldirector/nextjs:1 # Change this to your ghcr repo if you use ghcr instead
          imagePullPolicy: Always
          ports:
            - containerPort: 3000