kind: Secret
apiVersion: v1
metadata:
  name: argocd-github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/technicaldirector
  type: helm
  githubAppID: "1144539"
  githubAppInstallationID: "61013408"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----