apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
helmCharts:
- name: argo-cd
  namespace: argocd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  version: 7.8.4
resources:
- ./templates/namespaces/argocd-namespace.yaml
- ./templates/ingresses/argocd-ingress.yaml
- ./templates/secrets/argocd-secret.yaml
