apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
helmCharts:
- name: sealed-secrets
  namespace: kube-system
  releaseName: sealed-secrets-controller
  repo: https://bitnami-labs.github.io/sealed-secrets
  version: 2.17.1
