apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: technicaldirector/nextjs:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
