apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pgpool
resources:
- ./templates/namespaces/pgpool-namespace.yaml
- ./templates/secrets/pgpool-secret.yaml
- ./templates/configmaps/pgpool-configmap.yaml
- ./templates/deployments/pgpool-deployment.yaml
- ./templates/services/pgpool-service.yaml

sortOptions:
  order: fifo