apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cnpg
helmCharts:
- name: cloudnative-pg # Chart name
  namespace: cnpg # Namespace to deploy the chart
  releaseName: cloudnative-pg-operator # Release name
  repo: https://cloudnative-pg.github.io/charts
  valuesFile: values.yaml
  version: 0.23.0
resources:
- ./templates/namespaces/cloudnative-pg-namespace.yaml