kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nextjs-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/technicaldirector/k3s-default.git
    path: charts/nextjs/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nextjs
  syncPolicy:
    automated:
      selfHeal: true
