apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pgbouncer
resources:
  - templates/namespaces/pgbouncer-namespace.yaml
  - templates/secrets/pgbouncer-secret.yaml
  - templates/deployments/pgbouncer-deployment.yaml
  - templates/services/pgbouncer-service.yaml

sortOptions:
  order: fifo