apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsNonRoot: true
      containers:
        - name: pgpool
          image: bitnami/pgpool:4.6.0
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: pgpool
              containerPort: 5432
          env:
            # Backend Nodes
            - name: PGPOOL_BACKEND_NODES
              value: "0:postgresql-cluster-rw.cnpg-database.svc.cluster.local:5432,1:postgresql-cluster-ro.cnpg-database.svc.cluster.local:5432"
            
            # Credentials
            - name: PGPOOL_SR_CHECK_USER
              value: app
            - name: PGPOOL_SR_CHECK_PASSWORD_FILE
              value: /secrets/sr-check-password
            - name: PGPOOL_POSTGRES_USERNAME
              value: app
            - name: PGPOOL_POSTGRES_PASSWORD_FILE
              value: /secrets/postgres-password
            - name: PGPOOL_ADMIN_USERNAME
              value: app
            - name: PGPOOL_ADMIN_PASSWORD_FILE
              value: /secrets/admin-password
            
            # Load balancing
            - name: PGPOOL_ENABLE_LOAD_BALANCING
              value: "yes"
            - name: PGPOOL_DISABLE_LOAD_BALANCE_ON_WRITE
              value: "transaction"

            # Connection Settings
            - name: PGPOOL_RESERVED_CONNECTIONS
              value: '1'
            - name: PGPOOL_HEALTH_CHECK_PSQL_TIMEOUT
              value: "6"
            - name: PGPOOL_CHILD_LIFE_TIME
              value: ""

            # Custom Settings
            - name: PGPOOL_USER_HBA_FILE
              value: /opt/bitnami/pgpool/user_config/pool_hba.conf
            # - name: PGPOOL_USER_CONF_FILE
            #   value: /opt/bitnami/pgpool/user_config/pgpool.conf

            # Logs
            - name: PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT
              value: "yes"
            - name: PGPOOL_ENABLE_LOG_CONNECTIONS
              value: "yes"
            - name: PGPOOL_ENABLE_LOG_HOSTNAME
              value: "yes"

          volumeMounts:
            - name: pgpool-secrets
              mountPath: /secrets
              readOnly: true
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/pgpool/etc
              subPath: app-etc-dir
            - name: empty-dir
              mountPath: /opt/bitnami/pgpool/conf
              subPath: app-conf-dir
            - name: pgpool-user-config
              mountPath: /opt/bitnami/pgpool/user_config
              readOnly: true
            - name: empty-dir
              mountPath: /opt/bitnami/pgpool/tmp
              subPath: app-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/pgpool/logs
              subPath: app-logs-dir

      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: pgpool-user-config
          configMap:
            name: pgpool-config
        - name: pgpool-secrets
          secret:
            secretName: pgpool-secret