kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nextjs-ingress
  namespace: nextjs
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx  # Ensure this matches your Ingress Controller
  rules:
  - host: nextjs.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service  # Match the actual service name
            port:
              number: 3000  # Ensure the service has this port exposed
