repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    createNamespace: true
    version: v1.17.1
    values:
      - ./values.yaml
    set:
      - name: installCRDs
        value: true
