kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: reflector-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/technicaldirector/kubestudio.git
    path: charts/reflector/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true