apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: nextjs
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 3000   # The port your Ingress routes traffic to
      targetPort: 3000  # The port inside the container
